Repository uvicgse/project-virtual-team-2, pull requests merged in 2019-05, with the labels that each got.

#49 Prevent app from reloading when pressing F5
  index.js
Labels: High Priority, P4, Small, Sprint 1, bug

#50 Show most recent repositories, Fixes #7
  app/components/addRepository/add.repository.component.html
  app/components/addRepository/add.repository.component.ts
  app/components/app/app.component.ts
  app/misc/repo.ts
  app/misc/router.ts
  stylesheets/styles.css
Labels: High Priority, Medium, P7, Sprint 1, enhancement

#52 Fix Issue #8: Making a commit through visual git does not cause the graph to update
  app/misc/git.ts
Labels: P1, Sprint 1, bug

#59 Fix Issue #11: Prevent app from reloading when pressing F5 when window is blurred
  index.js
Labels: High Priority, P4, Small, Sprint 1, bug
