Repository uvicgse/project-virtual-team-2, pull requests merged in 2019-06, with the labels that each got.

#110 Improving changed/staged file CSS
  stylesheets/styles.css
Labels: enhancement, sprint 4

#128 Hotfix for issue #127: selected-commit-diff-panel bug
  app/components/app/app.component.html
  app/components/selectedCommitDiffPanel/selected.commit.diff.panel.component.ts
  app/misc/graphSetup.ts
  stylesheets/styles.css
Labels: Small, bug

#138 Feature: Improve stash: drop/branch
  README.md
  app/components/graphPanel/graph.panel.component.html
  app/components/graphPanel/graph.panel.component.ts
  app/components/header/header.component.html
  app/misc/color.ts
  app/misc/git.ts
  app/misc/graphSetup.ts
  app/misc/graphing.ts
  app/misc/repo.ts
  docs/show-tags-on-node-hover.md
  index.html
  package-lock.json
  stylesheets/styles.css
Labels: enhancement, sprint 4

#140 Revert "Implemented: Fix to 89, 101"
  app/components/header/header.component.html
  app/misc/git.ts
  app/misc/repo.ts
Labels: High Priority, help wanted
